<?php
session_start();

// Check if user is logged in and is admin
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'admin') {
    header('Location: login.php');
    exit();
}

// Database Configuration
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "yardsofgrace";

// Connect to database
$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Initial date range (last 30 days by default)
$defaultStartDate = date('Y-m-d', strtotime('-30 days'));
$defaultEndDate = date('Y-m-d');

// Get filter values if submitted
$startDate = isset($_GET['start_date']) ? $_GET['start_date'] : $defaultStartDate;
$endDate = isset($_GET['end_date']) ? $_GET['end_date'] : $defaultEndDate;
$reportType = isset($_GET['report_type']) ? $_GET['report_type'] : 'full';
$status = isset($_GET['status']) ? $_GET['status'] : 'all';
$orderBy = isset($_GET['order_by']) ? $_GET['order_by'] : 'id';
$orderDir = isset($_GET['order_dir']) ? $_GET['order_dir'] : 'ASC';

// Handle CSV download
if (isset($_GET['download_csv'])) {
    $reportType = $_GET['download_csv'];
    
    // Create reports directory if it doesn't exist
    $reportDir = __DIR__ . '/reports/';
    if (!file_exists($reportDir)) {
        mkdir($reportDir, 0777, true);
    }
    
    // Create a user-friendly filename with timestamp
    $timestamp = date('Y-m-d_H-i-s');
    $filename = "YardsOfGrace_{$reportType}_Report_{$timestamp}.csv";
    $filepath = $reportDir . $filename;
    
    // Open file with UTF-8 BOM for Excel compatibility
    $file = fopen($filepath, 'w');
    fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));

    // Write report header with increased spacing
    fputcsv($file, ['YARDS OF GRACE - DETAILED BUSINESS REPORT']);
    fputcsv($file, ['Generated On: ' . date('d/m/Y h:i A')]);
    fputcsv($file, ['Report Period: ' . date('d/m/Y', strtotime($startDate)) . ' to ' . date('d/m/Y', strtotime($endDate))]);
    fputcsv($file, ['Report Type: ' . ucfirst($reportType)]);
    fputcsv($file, ['Generated by: ' . $_SESSION['username']]);
    fputcsv($file, []);

    // --- USERS REPORT SECTION ---
    if ($reportType == 'full' || $reportType == 'users') {
        fputcsv($file, ['USER INFORMATION REPORT']);
        fputcsv($file, []);
        
        // Increased column widths significantly
        fputcsv($file, [
            str_pad('User ID', 15),
            str_pad('Username', 40),
            str_pad('Email Address', 60),
            str_pad('Account Type', 25),
            str_pad('Registration Date', 30)
        ]);
        
        // Add a separator line
        fputcsv($file, [
            str_repeat('-', 15),
            str_repeat('-', 40),
            str_repeat('-', 60),
            str_repeat('-', 25),
            str_repeat('-', 30)
        ]);
        
        $userQuery = "SELECT 
            id,
            username,
            email,
            role,
            created_at
        FROM users 
        WHERE 1=1" . 
        ($startDate && $endDate ? " AND created_at BETWEEN '$startDate 00:00:00' AND '$endDate 23:59:59'" : "") . 
        " ORDER BY " . (in_array($orderBy, ['id', 'username', 'email', 'role']) ? $orderBy : 'id') . " $orderDir";
        
        $userResult = $conn->query($userQuery);
        while ($row = $userResult->fetch_assoc()) {
            fputcsv($file, [
                str_pad($row['id'], 15),
                str_pad($row['username'], 40),
                str_pad($row['email'], 60),
                str_pad(ucfirst($row['role']), 25),
                str_pad(date('d/m/Y h:i A', strtotime($row['created_at'])), 30)
            ]);
        }
        
        fputcsv($file, []);
        fputcsv($file, ['Total Users: ' . $userResult->num_rows]);
        fputcsv($file, []);
        fputcsv($file, [str_repeat('=', 170)]); // Visual separator between sections
        fputcsv($file, []);
    }
    
    // --- ORDERS REPORT SECTION ---
    if ($reportType == 'full' || $reportType == 'orders') {
        fputcsv($file, ['ORDER TRANSACTION REPORT']);
        fputcsv($file, []);
        
        // Increased column widths
        fputcsv($file, [
            str_pad('Order ID', 15),
            str_pad('Customer Name', 40),
            str_pad('Order Date', 30),
            str_pad('Amount (₹)', 20),
            str_pad('Order Status', 25),
            str_pad('Payment Method', 30)
        ]);
        
        // Add a separator line
        fputcsv($file, [
            str_repeat('-', 15),
            str_repeat('-', 40),
            str_repeat('-', 30),
            str_repeat('-', 20),
            str_repeat('-', 25),
            str_repeat('-', 30)
        ]);
        
        $orderQuery = "SELECT 
            o.id,
            u.username,
            o.created_at,
            o.total_amount,
            o.order_status,
            o.payment_method
        FROM orders o
        INNER JOIN users u ON o.user_id = u.id 
        WHERE 1=1" . 
        ($startDate && $endDate ? " AND o.created_at BETWEEN '$startDate 00:00:00' AND '$endDate 23:59:59'" : "") .
        ($status != 'all' ? " AND o.order_status = '$status'" : "") .
        " ORDER BY " . ($orderBy == 'username' ? "u.username" : "o.$orderBy") . " $orderDir";

        $result = $conn->query($orderQuery);
        $totalAmount = 0;
        
        while ($row = $result->fetch_assoc()) {
            fputcsv($file, [
                str_pad($row['id'], 15),
                str_pad($row['username'], 40),
                str_pad(date('d/m/Y h:i A', strtotime($row['created_at'])), 30),
                str_pad('₹' . number_format($row['total_amount'], 2), 20),
                str_pad(ucfirst($row['order_status']), 25),
                str_pad(ucfirst($row['payment_method']), 30)
            ]);
            $totalAmount += $row['total_amount'];
        }
        
        fputcsv($file, []);
        fputcsv($file, ['Total Orders: ' . $result->num_rows]);
        fputcsv($file, ['Total Revenue: ₹' . number_format($totalAmount, 2)]);
        if ($result->num_rows > 0) {
            fputcsv($file, ['Average Order Value: ₹' . number_format($totalAmount/$result->num_rows, 2)]);
        }
        fputcsv($file, []);
        fputcsv($file, [str_repeat('=', 170)]); // Visual separator
        fputcsv($file, []);
    }
    
    // --- SAREE INVENTORY REPORT SECTION ---
    if ($reportType == 'full' || $reportType == 'sarees') {
        fputcsv($file, ['SAREE INVENTORY REPORT']);
        fputcsv($file, []);
        
        // Increased column widths
        fputcsv($file, [
            str_pad('Product ID', 15),
            str_pad('Saree Name', 60),
            str_pad('Color', 25),
            str_pad('Price (₹)', 20),
            str_pad('Stock', 15),
            str_pad('Last Updated', 30)
        ]);
        
        // Add a separator line
        fputcsv($file, [
            str_repeat('-', 15),
            str_repeat('-', 60),
            str_repeat('-', 25),
            str_repeat('-', 20),
            str_repeat('-', 15),
            str_repeat('-', 30)
        ]);
        
        $sareeQuery = "SELECT 
            id,
            name,
            color,
            price,
            stock,
            last_stock_update
        FROM sarees
        WHERE 1=1" . 
        ($startDate && $endDate ? " AND created_at BETWEEN '$startDate 00:00:00' AND '$endDate 23:59:59'" : "") .
        " ORDER BY " . (in_array($orderBy, ['id', 'name', 'price', 'stock']) ? $orderBy : 'id') . " $orderDir";
        
        $sareeResult = $conn->query($sareeQuery);
        $totalValue = 0;
        
        while ($row = $sareeResult->fetch_assoc()) {
            $stockValue = $row['price'] * $row['stock'];
            $totalValue += $stockValue;
            
            fputcsv($file, [
                str_pad($row['id'], 15),
                str_pad($row['name'], 60),
                str_pad(ucfirst($row['color']), 25),
                str_pad('₹' . number_format($row['price'], 2), 20),
                str_pad($row['stock'], 15),
                str_pad(date('d/m/Y h:i A', strtotime($row['last_stock_update'])), 30)
            ]);
        }
        
        fputcsv($file, []);
        fputcsv($file, ['Total Products: ' . $sareeResult->num_rows]);
        fputcsv($file, ['Total Inventory Value: ₹' . number_format($totalValue, 2)]);
    }
    
    fclose($file);
    
    // Force download with proper headers
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    readfile($filepath);
    exit();
}

// Rest of the code remains the same...
// (PDF generation and other functionality)

// Get order status options for dropdown
$statusOptions = array('all', 'pending', 'processing', 'shipped', 'delivered', 'cancelled', 'cash_received');

// Get column names for orderBy dropdown
$orderByColumns = array('id', 'username', 'name', 'total_amount', 'price', 'stock', 'created_at');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Reports - Yards of Grace</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="report.css">
</head>
<body>
    <div class="top-bar">
        <p>Free domestic shipping on orders above INR 10,000. International shipping available.</p>
    </div>

    <div class="header-main">
        <div class="header-center">
            <h1><img src="logo3.png" alt="Logo" width="50px">YARDS OF GRACE</h1>
        </div>
        <div class="nav-buttons">
            <a href="admin.php" class="dashboard-btn">
                <i class="fas fa-tachometer-alt"></i> Dashboard
            </a>
            <button class="logout-btn" onclick="window.location.href='logout.php'">
                <i class="fas fa-sign-out-alt"></i> Logout
            </button>
        </div>
    </div>

    <div class="main-container">
        <div class="page-title">
            <h1>Admin Reports</h1>
            <p>Generate and download reports to analyze your business data</p>
        </div>
        
        <!-- Filter section -->
        <div class="filter-section">
            <h3 class="filter-title"><i class="fas fa-filter"></i> Filter Report Data</h3>
            <form action="" method="GET" class="filter-form">
                <div class="form-group">
                    <label for="start_date">Start Date</label>
                    <input type="date" id="start_date" name="start_date" class="form-control" value="<?php echo $startDate; ?>">
                </div>
                <div class="form-group">
                    <label for="end_date">End Date</label>
                    <input type="date" id="end_date" name="end_date" class="form-control" value="<?php echo $endDate; ?>">
                </div>
                <div class="form-group">
                    <label for="report_type">Report Type</label>
                    <select id="report_type" name="report_type" class="form-control">
                        <option value="full" <?php echo $reportType == 'full' ? 'selected' : ''; ?>>Full Report</option>
                        <option value="users" <?php echo $reportType == 'users' ? 'selected' : ''; ?>>Users Only</option>
                        <option value="orders" <?php echo $reportType == 'orders' ? 'selected' : ''; ?>>Orders Only</option>
                        <option value="sarees" <?php echo $reportType == 'sarees' ? 'selected' : ''; ?>>Sarees Only</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="status">Order Status</label>
                    <select id="status" name="status" class="form-control">
                        <option value="all" <?php echo $status == 'all' ? 'selected' : ''; ?>>All Statuses</option>
                        <option value="pending" <?php echo $status == 'pending' ? 'selected' : ''; ?>>Pending</option>
                        <option value="processing" <?php echo $status == 'processing' ? 'selected' : ''; ?>>Processing</option>
                        <option value="shipped" <?php echo $status == 'shipped' ? 'selected' : ''; ?>>Shipped</option>
                        <option value="delivered" <?php echo $status == 'delivered' ? 'selected' : ''; ?>>Delivered</option>
                        <option value="cancelled" <?php echo $status == 'cancelled' ? 'selected' : ''; ?>>Cancelled</option>
                        <option value="cash_received" <?php echo $status == 'cash_received' ? 'selected' : ''; ?>>Cash Received</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="order_by">Sort By</label>
                    <select id="order_by" name="order_by" class="form-control">
                        <option value="id" <?php echo $orderBy == 'id' ? 'selected' : ''; ?>>ID</option>
                        <option value="username" <?php echo $orderBy == 'username' ? 'selected' : ''; ?>>Username</option>
                        <option value="name" <?php echo $orderBy == 'name' ? 'selected' : ''; ?>>Name</option>
                        <option value="total_amount" <?php echo $orderBy == 'total_amount' ? 'selected' : ''; ?>>Total Amount</option>
                        <option value="price" <?php echo $orderBy == 'price' ? 'selected' : ''; ?>>Price</option>
                        <option value="stock" <?php echo $orderBy == 'stock' ? 'selected' : ''; ?>>Stock</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="order_dir">Order</label>
                    <select id="order_dir" name="order_dir" class="form-control">
                        <option value="ASC" <?php echo $orderDir == 'ASC' ? 'selected' : ''; ?>>Ascending</option>
                        <option value="DESC" <?php echo $orderDir == 'DESC' ? 'selected' : ''; ?>>Descending</option>
                    </select>
                </div>
                
                <div class="filter-buttons">
                    <button type="reset" class="filter-btn reset-btn">
                        <i class="fas fa-undo"></i> Reset
                    </button>
                    <button type="submit" class="filter-btn apply-btn">
                        <i class="fas fa-check"></i> Apply Filters
                    </button>
                </div>
            </form>
        </div>
        
        <div class="reports-container">
            <div class="report-card full-report-card">
                <span class="format-badge pdf-badge">PDF</span>
                <span class="format-badge csv-badge">CSV</span>
                <div class="card-header">
                    <div class="card-icon">
                        <i class="fas fa-file-pdf"></i>
                    </div>
                    <div class="card-title">
                        <h2>Complete Business Report</h2>
                        <p>All-in-one comprehensive report</p>
                    </div>
                </div>
                <div class="card-content">
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-info-circle"></i> Description
                        </div>
                        <p>This complete report combines all business data in a single document, providing a comprehensive overview of your entire operation.</p>
                    </div>
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-list-ul"></i> Includes
                            <span class="help-icon">?
                                <span class="help-text">This report is comprehensive and may take longer to generate</span>
                            </span>
                        </div>
                        <ul class="feature-list">
                            <li>Complete user profile information</li>
                            <li>All orders with detailed status</li>
                            <li>Full inventory and stock levels</li>
                            <li>Organized by sections for easy reference</li>
                        </ul>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="?download=full<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo ($status != 'all' ? '&status='.$status : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn" onclick="showNotification('pdf-full')">
                        <i class="fas fa-file-pdf"></i> PDF Format
                    </a>
                    <a href="?download_csv=full<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo ($status != 'all' ? '&status='.$status : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn csv-btn" onclick="showNotification('csv-full')">
                        <i class="fas fa-file-csv"></i> CSV Format
                    </a>
                </div>
            </div>
            
            <div class="report-card">
                <span class="format-badge pdf-badge">PDF</span>
                <span class="format-badge csv-badge">CSV</span>
                <div class="card-header">
                    <div class="card-icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="card-title">
                        <h2>Users Report</h2>
                        <p>Customer & admin accounts data</p>
                    </div>
                </div>
                <div class="card-content">
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-info-circle"></i> Description
                        </div>
                        <p>Get detailed information about all registered users and admin accounts in your system.</p>
                    </div>
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-list-ul"></i> Includes
                        </div>
                        <ul class="feature-list">
                            <li>User IDs and usernames</li>
                            <li>Email addresses for communication</li>
                            <li>Account roles and permissions</li>
                            <li>Organized in tabular format</li>
                        </ul>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="?download=users<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn" onclick="showNotification('pdf-users')">
                        <i class="fas fa-file-pdf"></i> PDF Format
                    </a>
                    <a href="?download_csv=users<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn csv-btn" onclick="showNotification('csv-users')">
                        <i class="fas fa-file-csv"></i> CSV Format
                    </a>
                </div>
            </div>
            
            <div class="report-card">
                <span class="format-badge pdf-badge">PDF</span>
                <span class="format-badge csv-badge">CSV</span>
                <div class="card-header">
                    <div class="card-icon">
                        <i class="fas fa-shopping-cart"></i>
                    </div>
                    <div class="card-title">
                        <h2>Orders Report</h2>
                        <p>Transactions and order details</p>
                    </div>
                </div>
                <div class="card-content">
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-info-circle"></i> Description
                        </div>
                        <p>Analyze all customer orders and transactions with detailed status information.</p>
                    </div>
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-list-ul"></i> Includes
                        </div>
                        <ul class="feature-list">
                            <li>Order IDs and customer details</li>
                            <li>Total amount and payment methods</li>
                            <li>Current order status tracking</li>
                            <li>Date and time information</li>
                        </ul>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="?download=orders<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo ($status != 'all' ? '&status='.$status : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn" onclick="showNotification('pdf-orders')">
                        <i class="fas fa-file-pdf"></i> PDF Format
                    </a>
                    <a href="?download_csv=orders<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo ($status != 'all' ? '&status='.$status : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn csv-btn" onclick="showNotification('csv-orders')">
                        <i class="fas fa-file-csv"></i> CSV Format
                    </a>
                </div>
            </div>
            
            <div class="report-card">
                <span class="format-badge pdf-badge">PDF</span>
                <span class="format-badge csv-badge">CSV</span>
                <div class="card-header">
                    <div class="card-icon">
                        <i class="fas fa-tshirt"></i>
                    </div>
                    <div class="card-title">
                        <h2>Saree Inventory Report</h2>
                        <p>Stock levels and product data</p>
                    </div>
                </div>
                <div class="card-content">
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-info-circle"></i> Description
                        </div>
                        <p>Track your entire inventory with detailed information about each saree product.</p>
                    </div>
                    <div class="content-section">
                        <div class="section-title">
                            <i class="fas fa-list-ul"></i> Includes
                        </div>
                        <ul class="feature-list">
                            <li>Product IDs and detailed names</li>
                            <li>Current stock levels and pricing</li>
                            <li>Last stock update timestamps</li>
                            <li>Helps identify low stock items</li>
                        </ul>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="?download=sarees<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn" onclick="showNotification('pdf-sarees')">
                        <i class="fas fa-file-pdf"></i> PDF Format
                    </a>
                    <a href="?download_csv=sarees<?php echo (!empty($startDate) ? '&start_date='.$startDate : ''); ?><?php echo (!empty($endDate) ? '&end_date='.$endDate : ''); ?><?php echo (!empty($orderBy) ? '&order_by='.$orderBy : ''); ?><?php echo (!empty($orderDir) ? '&order_dir='.$orderDir : ''); ?>" class="download-btn csv-btn" onclick="showNotification('csv-sarees')">
                        <i class="fas fa-file-csv"></i> CSV Format
                    </a>
                </div>
            </div>
        </div>
        
        <div class="feedback-section">
            <h3>Need A Custom Report?</h3>
            <p>If you need a specialized report with specific metrics or format, our development team can help.</p>
            <button class="feedback-btn" onclick="window.location.href='contact_dev.php'">
                <i class="fas fa-comment-alt"></i> Request Custom Report
            </button>
        </div>
    </div>
    
    <div id="toast" class="toast-notification">
        <i class="fas fa-check-circle"></i> <span id="toast-message">Your report is being generated</span>
    </div>
    
    <script>
        function showNotification(type) {
            const toast = document.getElementById('toast');
            const toastMessage = document.getElementById('toast-message');
            
            let message = 'Your report is being generated';
            let format = 'PDF';
            
            if (type.startsWith('csv')) {
                format = 'CSV';
            }
            
            if (type.includes('full')) {
                message = `Your complete ${format} report is being generated`;
            } else if (type.includes('users')) {
                message = `Your users ${format} report is being generated`;
            } else if (type.includes('orders')) {
                message = `Your orders ${format} report is being generated`;
            } else if (type.includes('sarees')) {
                message = `Your inventory ${format} report is being generated`;
            }
            
            toastMessage.textContent = message;
            toast.style.display = 'block';
            
            setTimeout(function() {
                toast.style.opacity = '0';
                setTimeout(function() {
                    toast.style.display = 'none';
                    toast.style.opacity = '1';
                }, 300);
            }, 3000);
        }
        
        // Date validation
        document.querySelector('.filter-form').addEventListener('submit', function(e) {
            const startDate = document.getElementById('start_date').value;
            const endDate = document.getElementById('end_date').value;
            
            if (startDate && endDate && new Date(startDate) > new Date(endDate)) {
                e.preventDefault();
                alert('Start date cannot be after end date. Please correct your date selection.');
            }
        });
    </script>
</body>
</html>